/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogGroup: typeof import('./src/components/Modal/DialogGroup.vue')['default']
    Greeting: typeof import('./src/components/Greeting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestModal: typeof import('./src/components/Modal/TestModal.vue')['default']
    TIcon: typeof import('./src/components/TIcon.vue')['default']
    TInput: typeof import('./src/components/TInput.vue')['default']
    TInputComposed: typeof import('./src/components/TInputComposed.vue')['default']
    TSuspense: typeof import('./src/components/TSuspense.vue')['default']
    UserForm: typeof import('./src/components/Form/UserForm.vue')['default']
    UserList: typeof import('./src/components/Async/UserList.vue')['default']
  }
}
