/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    DialogGroup: typeof import('./src/components/Modal/DialogGroup.vue')['default']
    ErrorMessage: typeof import('vee-validate')['ErrorMessage']
    Field: typeof import('vee-validate')['Field']
    Form: typeof import('vee-validate')['Form']
    Greeting: typeof import('./src/components/Greeting.vue')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    NewLayout: typeof import('./src/layouts/NewLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/Form/SearchForm.vue')['default']
    Spinner: typeof import('./src/components/Modal/Spinner.vue')['default']
    TestModal: typeof import('./src/components/Modal/TestModal.vue')['default']
    TIcon: typeof import('./src/components/TIcon.vue')['default']
    TInput: typeof import('./src/components/TInput.vue')['default']
    TInputComposed: typeof import('./src/components/TInputComposed.vue')['default']
    TSearch: typeof import('./src/components/TSearch.vue')['default']
    TSuspense: typeof import('./src/components/TSuspense.vue')['default']
    UserForm: typeof import('./src/components/Form/UserForm.vue')['default']
    UserList: typeof import('./src/components/Async/UserList.vue')['default']
  }
}
